version: '3'
services:
  backend:
    build: ./vendor-backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:5173"
    restart: always
    depends_on:
      - backend
